---
apiVersion: v1
kind: Pod
metadata:
  name: spring4shell-pod
  labels:
    app: spring4shell
spec:
  containers:
    - name: spring4shell
      image: 022499044118.dkr.ecr.ap-northeast-2.amazonaws.com/spring4shell:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: vulmachine-pod
  labels:
    app: vulmachine
spec:
  containers:
    - name: vulmachine
      image: jieliau/vulmachine
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-ce", "tail -f /dev/null"]
---
apiVersion: v1
kind: Service
metadata:
  name: sprig4shell
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: spring4shell
  type: LoadBalancer
---
